"""
Cookbook Synthesizer Agent
Converts remediation plans into step-by-step DevOps runbook checklists.
"""

from orchestrator.state import IncidentAnalysisState, CookbookChecklist
from utils.llm_client import LLMClient


class CookbookAgent:
    """
    Agent responsible for creating actionable DevOps runbook checklists.
    Transforms remediation plans into executable procedures.
    """
    
    SYSTEM_PROMPT = """You are a DevOps Cookbook Specialist.

Your task is to convert technical remediation plans into clear, actionable runbook checklists that any on-call engineer can follow.

Guidelines:
1. Break down complex fixes into discrete, sequential steps
2. Each step should be specific and actionable
3. Include exact commands, file paths, or configuration changes
4. Add validation steps to verify fixes
5. Provide prerequisites (access, tools, permissions needed)
6. Include a rollback plan in case remediation causes issues
7. Use imperative voice ("Check...", "Restart...", "Verify...")
8. Number steps logically

Format as a DevOps runbook that could be saved and reused for similar incidents."""
    
    def __init__(self, llm_client: LLMClient):
        """
        Initialize Cookbook Agent
        
        Args:
            llm_client: LLM client for synthesis
        """
        self.llm = llm_client
    
    def synthesize_checklist(self, state: IncidentAnalysisState) -> CookbookChecklist:
        """
        Synthesize runbook checklist from remediation plan
        
        Args:
            state: Current state with remediation plan
            
        Returns:
            Cookbook checklist
        """
        incident = state.classified_incident
        remediation = state.remediation_plan
        
        user_prompt = f"""Create a DevOps runbook checklist for this incident:

INCIDENT:
- Type: {incident.incident_type}
- Severity: {incident.severity}
- Service: {incident.affected_service}

REMEDIATION PLAN:
Root Cause: {remediation.root_cause_hypothesis}

Recommended Fixes:
{chr(10).join(f"- {fix}" for fix in remediation.recommended_fixes)}

Rationale: {remediation.technical_rationale}

Transform this into a comprehensive runbook with:
1. Title (concise, descriptive)
2. Prerequisites (what you need before starting)
3. Checklist items (step-by-step actions)
4. Validation steps (how to verify the fix worked)
5. Rollback plan (how to undo changes if needed)

Make each step concrete and executable. Include commands, file paths, or specific actions."""
        
        checklist = self.llm.invoke_with_structured_output(
            system_prompt=self.SYSTEM_PROMPT,
            user_prompt=user_prompt,
            output_schema=CookbookChecklist
        )
        
        return checklist
    
    def format_as_markdown(self, checklist: CookbookChecklist) -> str:
        """
        Format checklist as markdown for display
        
        Args:
            checklist: Cookbook checklist
            
        Returns:
            Markdown formatted string
        """
        md = f"# {checklist.title}\n\n"
        
        if checklist.prerequisites:
            md += "## Prerequisites\n\n"
            for prereq in checklist.prerequisites:
                md += f"- {prereq}\n"
            md += "\n"
        
        md += "## Remediation Steps\n\n"
        for i, item in enumerate(checklist.checklist_items, 1):
            md += f"{i}. {item}\n"
        md += "\n"
        
        if checklist.validation_steps:
            md += "## Validation\n\n"
            for i, step in enumerate(checklist.validation_steps, 1):
                md += f"{i}. {step}\n"
            md += "\n"
        
        if checklist.rollback_plan:
            md += "## Rollback Plan\n\n"
            md += f"{checklist.rollback_plan}\n\n"
        
        md += "---\n*Generated by DevOps Incident Analysis Suite*\n"
        
        return md
    
    def process(self, state: IncidentAnalysisState) -> IncidentAnalysisState:
        """
        Main processing method for the agent
        
        Args:
            state: Current incident analysis state
            
        Returns:
            Updated state with cookbook checklist
        """
        try:
            if not state.remediation_plan:
                raise ValueError("No remediation plan available")
            
            # Synthesize checklist
            checklist = self.synthesize_checklist(state)
            
            # Update state
            state.cookbook_checklist = checklist
            
        except Exception as e:
            state.errors.append(f"Cookbook Agent Error: {str(e)}")
        
        return state
